Try to reopen database in case of unexpected closure
jakearchibald/idb-keyval pull request #175
Opened 2024-08-21 08:33 UTC by zarko-tg

It does not seems to be much activity on this project but here's comes a rather important PR for which hopefully we get feedback.

There (still) seems to be a problem with iOS Safari, where the database connection is unexpectedly closed. This is difficult to reproduce but it appears that it happens when an app has been active in the background for some time and the internet connection has been lost (and then maybe reestablished). It's also unclear whether this is caused by a bug in iOS Safari or the occasional unexpected closure is actually valid - behaving by design.

From what I could see idp-keyval does not seem to have any recovery logic to handle this case. I guess in practice this could mean that the functionality is broken until one kills/restarts the app.

Our error logs are now clogged with "InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing." reports and we're not really sure what's the effect of this on around 10% of our users/user sessions.

Same/similar reported issues are:
- https://github.com/jakearchibald/idb-keyval/issues/165
- https://github.com/jakearchibald/idb/issues/229

I've noticed that projects like Firebase (storage related) and Dexie have already taken measures for database connection recovery.

This PR is sort of a blind attempt to address the issue given the difficulty to reproduce, but we're testing it atm. It doesn't seem to cause any new issues/problems.

2024-10-16 15:31 UTC, bastienlemaitre commented
@jakearchibald can you merge this PR ? Thx

2024-10-16 16:08 UTC, jakearchibald commented
Thanks for the ping. I'll take a look.

2024-10-17 13:46 UTC, jkukatzkihuebinet commented
Implemented this yesterday for our app and seems to have mitigated the issue running on Chrome Android Devices.
+1 on getting this merged

2024-10-17 18:59 UTC, zarko-tg commented
Hi, it's been some time now since I filed this PR, so regardless whether it gets accepted or not, I feel like providing a little update for those affected.

We've been using a patched idb-keyval with the PR's code in a production Ionic/Capacitor app. It doesn't seems to cause any new problem but I cannot conclude that it actually helps much. That may sound strange but the reasons are the following:
- I still haven't been able to properly reproduce the original issue, even after searching for similar cases online.
- The original issue might be a side effect or a consequence of a bigger issue with iOS/Safari, namely that the database cannot be reopened, which is a major bummer. Some say a (technical) workaround is to kill/restart the app or restart the device. There are a number of bugs filed for WebKit and/or Capacitor on the matter, but sadly close to zero action from people who should have the knowledge to fix or remedy the issue.
- Because of the latter, our production error logs are now clogged / over quota, and we're not really sure what's going on out there. We don't know what it means in practice for the user experience.

2024-12-30 19:34 UTC, rgomezr391 commented
We're also seeing this issue on our production app and I just realized about the existence on this PR. 

Do we know if this going to be merged anytime soon?

2025-01-13 14:25 UTC, normanzb commented
it seems the PR is unlikely to be merged anytime soon, shall we release a new package with the fix?

2025-01-13 14:36 UTC, normanzb commented on src/util.ts
> +    console.assert(true, `Could not find database "${dbName}" to close.`);
why not simply `console.error`

2025-01-28 12:43 UTC, snowinszu commented
We encountered the same problem

2025-03-17 21:15 UTC, jonarnaldo commented
seeing the same issue as well.

2025-04-30 05:20 UTC, Hari-Narayan-dev commented
we are facing similar issue on safari, any progress on this, are the changes fine and we are planning to merge this?

2025-05-01 16:01 UTC, DaddyWarbucks commented
I do not currently. But I just wrapped up my usage in some try/catches with consoles about keys and payloads. I am going to push it out into the wild now and hopefully I can have some feedback in a few days. 👍

2025-05-08 12:18 UTC, jakearchibald commented
I've attempted a smaller fix in 32443d03bf6592445ddc4043b329f42e0092e89f and it's published as 6.2.2. Please test this folks. Let me know if it solves the issue.

It relies on Safari firing the close event when it closes the database. If it doesn't, I can add more code to try to detect the error and trigger a reopen-and-retry.

2025-06-11 20:09 UTC, jstayton commented
@jakearchibald Your fix has definitely helped. Thanks! We saw

> Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

about 140 times in the 7 days before updating to v6.2.2, but only 1 time in the 7 days after.

I'm not sure if it's related, but a new error has appeared about 30 times in the 7 days after:

> Connection to Indexed Database server lost. Refresh the page to try again

Perhaps that was just being masked/trumped by the previous error?

2025-06-11 20:15 UTC, DaddyWarbucks commented
I can report the same as above. I am receiving substantially fewer errors since the update. And I am also receiving the `Connection to Indexed Database server lost. Refresh the page to try again` error. Thanks for the updates so far!

2025-06-14 10:28 UTC, jakearchibald commented
Are those errors also Safari only? I assume so, since I see that string in WebKit's source.

2025-06-23 21:29 UTC, jstayton commented
Yes, all are from WebKit (Mobile Safari or Chrome on iOS).

2025-06-24 08:56 UTC, jakearchibald commented
Sigh. It's so funny that they put "refresh the page" in an error that's developer facing, not user facing.

2025-09-03 07:35 UTC, l2cri requested changes

2025-09-03 07:35 UTC, l2cri commented on src/util.ts
> +    const request = indexedDB.open(dbName);
Error 
 `Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.`
 indexedDB.open need to use new version.
 If you add new table in DB you see that error

2025-10-06 03:23 UTC, xfsnowind commented
We met this issue in the Chrome in both Windows and Mac with version `6.2.2`, it's caused when calling api `createStore`:
> InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

When debug, it points to this line:
```
return (txMode, callback) =>
    getDB().then((db) =>
      callback(db.transaction(storeName, txMode).objectStore(storeName)), <--- THIS LINE
    );
```

2026-06-03 10:06 UTC, zarko-tg commented
Closing as stale / outdated.

2026-06-03 10:06 UTC, closed without merging